# Generated by Django 4.2.11 on 2024-07-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ican', '0016_businessdata_reg_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_post', models.CharField(max_length=30)),
                ('job_position', models.CharField(max_length=100)),
                ('upload_date', models.DateField()),
                ('job_timing', models.CharField(max_length=30)),
                ('company_title', models.CharField(max_length=100)),
                ('job_description', models.CharField(default='Best place to work', max_length=500)),
                ('Skill_1', models.CharField(max_length=100)),
                ('Skill_2', models.CharField(blank=True, max_length=100)),
                ('Skill_3', models.CharField(blank=True, max_length=100)),
                ('Skill_4', models.CharField(blank=True, max_length=100)),
                ('Skill_5', models.CharField(blank=True, max_length=100)),
                ('job_city', models.CharField(max_length=30)),
                ('job_Address', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=10)),
                ('email_id', models.EmailField(blank=True, max_length=60)),
                ('website_link', models.CharField(blank=True, max_length=100)),
                ('gmaps_link', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
