# Generated by Django 4.2.11 on 2024-07-13 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ican', '0017_jobdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdata',
            old_name='Skill_1',
            new_name='skill_1',
        ),
        migrations.RenameField(
            model_name='jobdata',
            old_name='Skill_2',
            new_name='skill_2',
        ),
        migrations.RenameField(
            model_name='jobdata',
            old_name='Skill_3',
            new_name='skill_3',
        ),
        migrations.RenameField(
            model_name='jobdata',
            old_name='Skill_5',
            new_name='skill_5',
        ),
    ]
