# Generated by Django 4.2.11 on 2024-07-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ican', '0018_rename_skill_1_jobdata_skill_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdata',
            old_name='Skill_4',
            new_name='skill_4',
        ),
        migrations.AlterField(
            model_name='jobdata',
            name='skill_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jobdata',
            name='upload_date',
            field=models.CharField(max_length=20),
        ),
    ]
