# Generated by Django 4.2.11 on 2024-07-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ican', '0019_rename_skill_4_jobdata_skill_4_alter_jobdata_skill_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdata',
            name='company_title',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='jobdata',
            name='job_position',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='jobdata',
            name='skill_1',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='jobdata',
            name='skill_2',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='jobdata',
            name='skill_3',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='jobdata',
            name='skill_4',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='jobdata',
            name='skill_5',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
