# Generated by Django 4.2.11 on 2024-07-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ican', '0020_alter_jobdata_company_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdata',
            name='skill_1',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='skill_2',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='skill_3',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='skill_4',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='skill_5',
        ),
        migrations.AlterField(
            model_name='jobdata',
            name='job_description',
            field=models.CharField(default='Best place to work', max_length=300),
        ),
    ]
