# Generated by Django 4.2.11 on 2024-07-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ican', '0021_remove_jobdata_skill_1_remove_jobdata_skill_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdata',
            name='job_description',
            field=models.TextField(default='Best place to work', max_length=300),
        ),
    ]
