# Generated by Django 4.2.11 on 2024-07-18 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ican', '0022_alter_jobdata_job_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdata',
            name='created_at',
        ),
    ]
