# Generated by Django 4.2.11 on 2024-07-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ican', '0023_remove_jobdata_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdata',
            name='skill_1',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='skill_2',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='skill_3',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='skill_4',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='skill_5',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
