# Generated by Django 4.2.11 on 2024-07-18 05:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ican', '0024_jobdata_skill_1_jobdata_skill_2_jobdata_skill_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
